import { db, courts } from "@workspace/db";

const courtData = [
  // ─── NEW YORK ───────────────────────────────────────────────
  {
    state: "NY", county: "New York",
    courtName: "Manhattan Civil Court – Small Claims",
    courtType: "Small Claims",
    maxClaim: 10000,
    address: "111 Centre St, New York, NY 10013",
    filingRoom: "Room 124",
    filingHours: "Mon–Fri 9am–5pm",
    phone: "(646) 386-5731",
    filingFee: 20,
    serviceFeeMin: 50, serviceFeeMax: 75,
    onlineFiling: false,
    onlineUrl: null,
    paymentMethods: "Cash, Money Order",
    notes: "Bring 3 copies of all documents. Hearings held evenings.",
  },
  {
    state: "NY", county: "Kings",
    courtName: "Brooklyn Civil Court – Small Claims",
    courtType: "Small Claims",
    maxClaim: 10000,
    address: "141 Livingston St, Brooklyn, NY 11201",
    filingRoom: "Room 607",
    filingHours: "Mon–Fri 9am–5pm",
    phone: "(347) 404-9130",
    filingFee: 20,
    serviceFeeMin: 50, serviceFeeMax: 75,
    onlineFiling: false,
    onlineUrl: null,
    paymentMethods: "Cash, Money Order",
    notes: "Hearings typically scheduled evenings.",
  },
  {
    state: "NY", county: "Queens",
    courtName: "Queens Civil Court – Small Claims",
    courtType: "Small Claims",
    maxClaim: 10000,
    address: "89-17 Sutphin Blvd, Jamaica, NY 11435",
    filingRoom: "Room 160",
    filingHours: "Mon–Fri 9am–5pm",
    phone: "(718) 262-7123",
    filingFee: 20,
    serviceFeeMin: 50, serviceFeeMax: 75,
    onlineFiling: false,
    onlineUrl: null,
    paymentMethods: "Cash, Money Order",
    notes: "Parking garage adjacent to building.",
  },
  {
    state: "NY", county: "Bronx",
    courtName: "Bronx Civil Court – Small Claims",
    courtType: "Small Claims",
    maxClaim: 10000,
    address: "851 Grand Concourse, Bronx, NY 10451",
    filingRoom: "Room 122",
    filingHours: "Mon–Fri 9am–5pm",
    phone: "(718) 618-2500",
    filingFee: 20,
    serviceFeeMin: 50, serviceFeeMax: 75,
    onlineFiling: false,
    onlineUrl: null,
    paymentMethods: "Cash, Money Order",
    notes: null,
  },
  {
    state: "NY", county: "Richmond",
    courtName: "Staten Island Civil Court – Small Claims",
    courtType: "Small Claims",
    maxClaim: 10000,
    address: "927 Castleton Ave, Staten Island, NY 10310",
    filingRoom: "Room 101",
    filingHours: "Mon–Fri 9am–5pm",
    phone: "(718) 675-8449",
    filingFee: 20,
    serviceFeeMin: 50, serviceFeeMax: 75,
    onlineFiling: false,
    onlineUrl: null,
    paymentMethods: "Cash, Money Order",
    notes: null,
  },
  {
    state: "NY", county: "Nassau",
    courtName: "Nassau County District Court – Small Claims",
    courtType: "Small Claims",
    maxClaim: 5000,
    address: "99 Main St, Hempstead, NY 11550",
    filingRoom: "Clerk's Office – Room 102",
    filingHours: "Mon–Fri 9am–5pm",
    phone: "(516) 572-2355",
    filingFee: 20,
    serviceFeeMin: 40, serviceFeeMax: 55,
    onlineFiling: false,
    onlineUrl: null,
    paymentMethods: "Cash, Money Order, Credit Card",
    notes: "Parking available behind building.",
  },
  {
    state: "NY", county: "Suffolk",
    courtName: "Suffolk County District Court – Small Claims",
    courtType: "Small Claims",
    maxClaim: 5000,
    address: "400 Carleton Ave, Central Islip, NY 11722",
    filingRoom: "Clerk Window",
    filingHours: "Mon–Fri 9am–4pm",
    phone: "(631) 853-7532",
    filingFee: 20,
    serviceFeeMin: 40, serviceFeeMax: 55,
    onlineFiling: false,
    onlineUrl: null,
    paymentMethods: "Cash, Money Order",
    notes: null,
  },
  {
    state: "NY", county: "Westchester",
    courtName: "Westchester County Court – Small Claims",
    courtType: "Small Claims",
    maxClaim: 5000,
    address: "111 Grove St, White Plains, NY 10601",
    filingRoom: "Room 800",
    filingHours: "Mon–Fri 9am–5pm",
    phone: "(914) 824-5300",
    filingFee: 15,
    serviceFeeMin: 35, serviceFeeMax: 50,
    onlineFiling: false,
    onlineUrl: null,
    paymentMethods: "Cash, Money Order, Check",
    notes: null,
  },
  {
    state: "NY", county: "Erie",
    courtName: "Buffalo City Court – Small Claims",
    courtType: "Small Claims",
    maxClaim: 5000,
    address: "50 Delaware Ave, Buffalo, NY 14202",
    filingRoom: "Room 301",
    filingHours: "Mon–Fri 9am–4pm",
    phone: "(716) 845-2600",
    filingFee: 15,
    serviceFeeMin: 30, serviceFeeMax: 50,
    onlineFiling: false,
    onlineUrl: null,
    paymentMethods: "Cash, Money Order",
    notes: null,
  },
  {
    state: "NY", county: "Monroe",
    courtName: "Rochester City Court – Small Claims",
    courtType: "Small Claims",
    maxClaim: 5000,
    address: "99 Exchange Blvd, Rochester, NY 14614",
    filingRoom: "Room 6",
    filingHours: "Mon–Fri 9am–4pm",
    phone: "(585) 428-2444",
    filingFee: 15,
    serviceFeeMin: 30, serviceFeeMax: 50,
    onlineFiling: false,
    onlineUrl: null,
    paymentMethods: "Cash, Money Order, Check",
    notes: null,
  },
  {
    state: "NY", county: "Onondaga",
    courtName: "Syracuse City Court – Small Claims",
    courtType: "Small Claims",
    maxClaim: 5000,
    address: "505 S State St, Syracuse, NY 13202",
    filingRoom: "Room 130",
    filingHours: "Mon–Fri 9am–4:30pm",
    phone: "(315) 671-2783",
    filingFee: 15,
    serviceFeeMin: 30, serviceFeeMax: 45,
    onlineFiling: false,
    onlineUrl: null,
    paymentMethods: "Cash, Money Order",
    notes: null,
  },
  {
    state: "NY", county: "Albany",
    courtName: "Albany City Court – Small Claims",
    courtType: "Small Claims",
    maxClaim: 5000,
    address: "24 Eagle St, Albany, NY 12207",
    filingRoom: "Room 209",
    filingHours: "Mon–Fri 8:30am–4pm",
    phone: "(518) 453-4640",
    filingFee: 15,
    serviceFeeMin: 30, serviceFeeMax: 45,
    onlineFiling: false,
    onlineUrl: null,
    paymentMethods: "Cash, Money Order",
    notes: null,
  },
  // ─── ILLINOIS ───────────────────────────────────────────────
  {
    state: "IL", county: "Cook",
    courtName: "Cook County Circuit Court – Small Claims",
    courtType: "Small Claims",
    maxClaim: 10000,
    address: "50 W Washington St, Chicago, IL 60602",
    filingRoom: "Room 601 – Richard J. Daley Center",
    filingHours: "Mon–Fri 8:30am–4:30pm",
    phone: "(312) 603-5030",
    filingFee: 85,
    serviceFeeMin: 60, serviceFeeMax: 80,
    onlineFiling: true,
    onlineUrl: "https://courtclerk.org/records-information/online-case-management/",
    paymentMethods: "Cash, Credit Card, Money Order",
    notes: "eFile available through approved vendors. Service by sheriff recommended.",
  },
  {
    state: "IL", county: "DuPage",
    courtName: "DuPage County Circuit Court – Small Claims",
    courtType: "Small Claims",
    maxClaim: 10000,
    address: "505 N County Farm Rd, Wheaton, IL 60187",
    filingRoom: "Clerk's Office – 1st Floor",
    filingHours: "Mon–Fri 8:30am–4:30pm",
    phone: "(630) 407-8700",
    filingFee: 80,
    serviceFeeMin: 50, serviceFeeMax: 70,
    onlineFiling: true,
    onlineUrl: "https://www.dupageco.org/courts/",
    paymentMethods: "Cash, Check, Credit Card",
    notes: "Free parking available on site.",
  },
  {
    state: "IL", county: "Lake",
    courtName: "Lake County Circuit Court – Small Claims",
    courtType: "Small Claims",
    maxClaim: 10000,
    address: "18 N County St, Waukegan, IL 60085",
    filingRoom: "Clerk's Office – 2nd Floor",
    filingHours: "Mon–Fri 8:30am–4:30pm",
    phone: "(847) 377-3380",
    filingFee: 75,
    serviceFeeMin: 50, serviceFeeMax: 65,
    onlineFiling: false,
    onlineUrl: null,
    paymentMethods: "Cash, Check, Money Order",
    notes: null,
  },
  {
    state: "IL", county: "Winnebago",
    courtName: "Winnebago County Circuit Court – Small Claims",
    courtType: "Small Claims",
    maxClaim: 10000,
    address: "400 W State St, Rockford, IL 61101",
    filingRoom: "Room 360",
    filingHours: "Mon–Fri 8:30am–4:30pm",
    phone: "(815) 319-4900",
    filingFee: 60,
    serviceFeeMin: 40, serviceFeeMax: 60,
    onlineFiling: false,
    onlineUrl: null,
    paymentMethods: "Cash, Check",
    notes: null,
  },
  // ─── OHIO ───────────────────────────────────────────────────
  {
    state: "OH", county: "Franklin",
    courtName: "Franklin County Municipal Court – Small Claims",
    courtType: "Small Claims",
    maxClaim: 6000,
    address: "375 S High St, Columbus, OH 43215",
    filingRoom: "Clerk's Office – 3rd Floor",
    filingHours: "Mon–Fri 8am–4pm",
    phone: "(614) 645-8224",
    filingFee: 60,
    serviceFeeMin: 25, serviceFeeMax: 45,
    onlineFiling: true,
    onlineUrl: "https://fcmcclerk.com/smallclaims",
    paymentMethods: "Cash, Credit Card, Check",
    notes: "Online filing available. Certified mail service included in fee.",
  },
  {
    state: "OH", county: "Cuyahoga",
    courtName: "Cleveland Municipal Court – Small Claims",
    courtType: "Small Claims",
    maxClaim: 6000,
    address: "1200 Ontario St, Cleveland, OH 44113",
    filingRoom: "Room 15-A",
    filingHours: "Mon–Fri 8am–4pm",
    phone: "(216) 664-4944",
    filingFee: 65,
    serviceFeeMin: 30, serviceFeeMax: 50,
    onlineFiling: false,
    onlineUrl: null,
    paymentMethods: "Cash, Money Order, Credit Card",
    notes: null,
  },
  {
    state: "OH", county: "Hamilton",
    courtName: "Hamilton County Municipal Court – Small Claims",
    courtType: "Small Claims",
    maxClaim: 6000,
    address: "1000 Main St, Cincinnati, OH 45202",
    filingRoom: "Room 390",
    filingHours: "Mon–Fri 8am–4:30pm",
    phone: "(513) 946-5200",
    filingFee: 55,
    serviceFeeMin: 25, serviceFeeMax: 40,
    onlineFiling: false,
    onlineUrl: null,
    paymentMethods: "Cash, Check, Credit Card",
    notes: null,
  },
  {
    state: "OH", county: "Summit",
    courtName: "Akron Municipal Court – Small Claims",
    courtType: "Small Claims",
    maxClaim: 6000,
    address: "217 S High St, Akron, OH 44308",
    filingRoom: "Room 103",
    filingHours: "Mon–Fri 8am–4pm",
    phone: "(330) 375-2120",
    filingFee: 55,
    serviceFeeMin: 25, serviceFeeMax: 40,
    onlineFiling: false,
    onlineUrl: null,
    paymentMethods: "Cash, Money Order",
    notes: null,
  },
  // ─── PENNSYLVANIA ───────────────────────────────────────────
  {
    state: "PA", county: "Philadelphia",
    courtName: "Philadelphia Municipal Court – Small Claims",
    courtType: "Small Claims",
    maxClaim: 12000,
    address: "1339 Chestnut St, Philadelphia, PA 19107",
    filingRoom: "Room 175",
    filingHours: "Mon–Fri 8:30am–4pm",
    phone: "(215) 686-7990",
    filingFee: 113,
    serviceFeeMin: 30, serviceFeeMax: 50,
    onlineFiling: false,
    onlineUrl: null,
    paymentMethods: "Cash, Credit Card, Money Order",
    notes: "File at the Civil Court filing counter. Bring ID and 2 copies of all documents.",
  },
  {
    state: "PA", county: "Allegheny",
    courtName: "Allegheny County Magisterial District Court – Small Claims",
    courtType: "Small Claims",
    maxClaim: 12000,
    address: "436 Grant St, Pittsburgh, PA 15219",
    filingRoom: "Prothonotary's Office – Room 101",
    filingHours: "Mon–Fri 8:30am–4pm",
    phone: "(412) 350-5300",
    filingFee: 90,
    serviceFeeMin: 30, serviceFeeMax: 50,
    onlineFiling: false,
    onlineUrl: null,
    paymentMethods: "Cash, Check, Credit Card",
    notes: "Cases heard at local Magisterial District Judge offices.",
  },
  {
    state: "PA", county: "Delaware",
    courtName: "Delaware County Magisterial District Court – Small Claims",
    courtType: "Small Claims",
    maxClaim: 12000,
    address: "201 W Front St, Media, PA 19063",
    filingRoom: "Clerk's Office – 1st Floor",
    filingHours: "Mon–Fri 8:30am–4pm",
    phone: "(610) 891-4000",
    filingFee: 85,
    serviceFeeMin: 25, serviceFeeMax: 45,
    onlineFiling: false,
    onlineUrl: null,
    paymentMethods: "Cash, Check",
    notes: null,
  },
  {
    state: "PA", county: "Montgomery",
    courtName: "Montgomery County Magisterial District Court – Small Claims",
    courtType: "Small Claims",
    maxClaim: 12000,
    address: "2 E Airy St, Norristown, PA 19401",
    filingRoom: "Clerk of Courts – Room 101",
    filingHours: "Mon–Fri 8:30am–4:30pm",
    phone: "(610) 278-3360",
    filingFee: 85,
    serviceFeeMin: 25, serviceFeeMax: 45,
    onlineFiling: false,
    onlineUrl: null,
    paymentMethods: "Cash, Check",
    notes: null,
  },
  {
    state: "PA", county: "Bucks",
    courtName: "Bucks County Magisterial District Court – Small Claims",
    courtType: "Small Claims",
    maxClaim: 12000,
    address: "55 E Court St, Doylestown, PA 18901",
    filingRoom: "Clerk of Courts",
    filingHours: "Mon–Fri 8:30am–4:30pm",
    phone: "(215) 348-6191",
    filingFee: 85,
    serviceFeeMin: 25, serviceFeeMax: 45,
    onlineFiling: false,
    onlineUrl: null,
    paymentMethods: "Cash, Check, Money Order",
    notes: null,
  },
];

async function seed() {
  console.log(`Seeding ${courtData.length} courts...`);
  for (const c of courtData) {
    await db
      .insert(courts)
      .values(c as any)
      .onConflictDoNothing();
  }
  console.log("Done.");
  process.exit(0);
}

seed().catch((e) => { console.error(e); process.exit(1); });
