import { Shield } from "lucide-react";

export function Disclaimer() {
  return (
    <div className="max-w-3xl mx-auto px-4 py-12">
      <div className="flex items-center gap-3 mb-6">
        <div className="w-9 h-9 bg-primary/10 rounded-lg flex items-center justify-center">
          <Shield className="w-5 h-5 text-primary" />
        </div>
        <h1 className="font-serif text-2xl font-bold text-foreground">Legal Disclaimer</h1>
      </div>

      <div className="bg-card border border-card-border rounded-lg p-6 space-y-5 text-sm text-muted-foreground leading-relaxed">
        <section>
          <h2 className="text-base font-semibold text-foreground mb-2">Not a Law Firm</h2>
          <p>
            SmallClaims AI is a self-help technology platform. It is not a law firm, does not employ attorneys,
            and does not provide legal advice, legal representation, or legal counsel of any kind. Use of this
            platform does not create an attorney-client relationship.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-foreground mb-2">General Information Only</h2>
          <p>
            All content, tools, and documents generated by this platform are provided for general informational
            and self-help purposes only. The information provided may not reflect the most current legal
            developments and may not apply to your specific situation, jurisdiction, or facts.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-foreground mb-2">You Are Responsible for Your Filing</h2>
          <p>
            You are solely responsible for reviewing, verifying, correcting, and filing any documents generated
            by this platform. Court procedures, filing requirements, fees, and deadlines vary by jurisdiction and
            may change at any time. Always verify current requirements with your local courthouse before filing.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-foreground mb-2">No Guarantee of Outcome</h2>
          <p>
            We do not guarantee any legal outcome, the success of your case, the enforceability of any judgment,
            or the accuracy of information generated by our AI tools. AI-generated content may contain errors
            and should always be reviewed carefully before submission.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-foreground mb-2">Consult an Attorney</h2>
          <p>
            If your situation is complex, involves significant amounts of money, or you are unsure of your rights
            and obligations, you should consult a licensed attorney in your jurisdiction before filing any legal
            document.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-foreground mb-2">Assumption of Risk</h2>
          <p>
            By using this platform, you acknowledge and agree that you use it at your own discretion and risk.
            SmallClaims AI, its owners, operators, and affiliates shall not be liable for any damages arising
            from your use of this platform or reliance on any content or documents generated by it.
          </p>
        </section>
      </div>

      <p className="text-xs text-muted-foreground text-center mt-6">
        Last updated: April 2026 &nbsp;·&nbsp; SmallClaims AI is an independent technology service.
      </p>
    </div>
  );
}
