import { FileText } from "lucide-react";

export function Terms() {
  return (
    <div className="max-w-3xl mx-auto px-4 py-12">
      <div className="flex items-center gap-3 mb-6">
        <div className="w-9 h-9 bg-primary/10 rounded-lg flex items-center justify-center">
          <FileText className="w-5 h-5 text-primary" />
        </div>
        <h1 className="font-serif text-2xl font-bold text-foreground">Terms of Service</h1>
      </div>

      <div className="bg-card border border-card-border rounded-lg p-6 space-y-5 text-sm text-muted-foreground leading-relaxed">
        <p>
          By using this platform, you agree to these Terms of Service. If you do not agree, do not use the service.
        </p>

        <section>
          <h2 className="text-base font-semibold text-foreground mb-2">1. Not Legal Advice</h2>
          <p>
            This platform provides self-help tools and general information only. It is not a law firm and does not
            provide legal advice, legal representation, or legal counsel of any kind. No attorney-client relationship
            is created through use of this service.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-foreground mb-2">2. User Responsibility</h2>
          <p>
            You are responsible for reviewing all documents before filing. Laws vary by jurisdiction and your
            situation may require professional advice. Always verify current court requirements with your local
            courthouse before submitting any documents.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-foreground mb-2">3. No Guarantee of Outcome</h2>
          <p>
            We do not guarantee any legal outcome, including the success of your claim, court acceptance of any
            documents, or enforcement of any judgment. AI-generated content may contain errors and should be
            reviewed carefully.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-foreground mb-2">4. Payments</h2>
          <p>
            Payments are one-time charges for access to document generation and related services. By completing a
            payment, you authorize the charge for the stated amount.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-foreground mb-2">5. Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by law, we are not liable for any direct, indirect, incidental, or
            consequential damages resulting from use of this service, including errors in documents, rejected
            filings, or case outcomes.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-foreground mb-2">6. Use at Your Own Risk</h2>
          <p>
            You agree to use this platform at your own discretion and risk. We make no representations that the
            service is appropriate or available for use in your jurisdiction.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-foreground mb-2">7. Changes</h2>
          <p>
            We may update these Terms at any time. Continued use of the platform after changes constitutes your
            acceptance of the updated Terms.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-foreground mb-2">8. Disclaimer of Warranties</h2>
          <p>
            This service is provided "as is" without warranties of any kind, express or implied. We do not
            guarantee the accuracy, completeness, or suitability of any content or documents generated for your
            specific legal situation.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-foreground mb-2">9. Indemnification</h2>
          <p>
            You agree to indemnify and hold harmless SmallClaims AI, its owners, operators, and affiliates from
            any claims, damages, losses, or legal actions arising from your use of the service or reliance on any
            documents or information generated by it.
          </p>
        </section>
      </div>

      <p className="text-xs text-muted-foreground text-center mt-6">
        Last updated: April 2026 &nbsp;·&nbsp; SmallClaims AI
      </p>
    </div>
  );
}
